In [43]:
import pandas as pd

from sklearn import neighbors
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [44]:
wifidf = pd.read_csv('trainingData.csv')
validationdf = pd.read_csv('validationData.csv')

In [45]:
#wifidf['df'] = 'training'
#validationdf['df'] = 'validation'
alldf = pd.concat([wifidf, validationdf])

In [15]:
#wifidf, validationdf = train_test_split(alldf,test_size=0.25)

In [46]:
validationdf = pd.read_csv('TEST_DATA.csv')

In [47]:
wifidf = alldf.drop(['SPACEID', 'RELATIVEPOSITION', 'USERID', 'PHONEID', 'TIMESTAMP'], axis = 1)
validationdf = validationdf.drop(['LONGITUDE', 'LATITUDE', 'FLOOR', 'BUILDINGID','SPACEID', 'RELATIVEPOSITION', 'USERID', 'PHONEID', 'TIMESTAMP'], axis = 1)

In [48]:
wifidf

,WAP001,WAP002,WAP003,WAP004,WAP005,WAP006,WAP007,WAP008,WAP009,WAP010,...,WAP515,WAP516,WAP517,WAP518,WAP519,WAP520,LONGITUDE,LATITUDE,FLOOR,BUILDINGID
0,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7541.264300,4.864921e+06,2,1
1,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7536.621200,4.864934e+06,2,1
2,100,100,100,100,100,100,100,-97,100,100,...,100,100,100,100,100,100,-7519.152400,4.864950e+06,2,1
3,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7524.570400,4.864934e+06,2,1
4,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7632.143600,4.864982e+06,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7317.344231,4.864796e+06,3,2
1107,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7313.731120,4.864792e+06,3,2
1108,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7637.535798,4.864903e+06,0,0
1109,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7636.654005,4.864905e+06,0,0
1110,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,-7637.944120,4.864904e+06,0,0

In [49]:
validationdf

,WAP001,WAP002,WAP003,WAP004,WAP005,WAP006,WAP007,WAP008,WAP009,WAP010,...,WAP511,WAP512,WAP513,WAP514,WAP515,WAP516,WAP517,WAP518,WAP519,WAP520
0,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
1,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
2,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
3,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
4,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5174,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
5175,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
5176,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
5177,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
5178,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100

In [50]:
wifidf.to_csv('wifidfnew.csv')
validationdf.to_csv('validationdfnew.csv')

In [51]:
wifidf = pd.read_csv('wifidfnew.csv')
validationdf = pd.read_csv('validationdfnew.csv')

In [22]:
# We'll start with building prediction, as it's the easiest one:

In [52]:
# Feature selection:
X_train = wifidf.iloc[:, 1:521]
y_train = wifidf.iloc[:, 524]

In [53]:
#Testing Set (X Testing)
X_validation = validationdf.iloc[:, 1:521]
#y_validation = validationdf.iloc[:, 524]

In [54]:
modellm = LogisticRegression()
modellm.fit(X_train,y_train)

C:\Users\xenia\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\xenia\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [55]:
predictions = modellm.predict(X_validation)
predictions

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [27]:
y_validation

NameError: name 'y_validation' is not defined

In [14]:
confusion = confusion_matrix(y_validation, predictions)
print("Confusion matrix:\n{}".format(confusion))

Confusion matrix:
[[1442    0    0]
 [   0 1381   12]
 [   0    1 2426]]

In [15]:
accuracy = accuracy_score(y_validation, predictions)
accuracy

0.9975294564804257

In [56]:
predictions = pd.DataFrame(predictions)
predictions.columns = ['BUILDINGID']
wifidfwithbuilding = pd.concat([X_validation, predictions], axis=1)
wifidfwithbuilding.to_csv('validationwithbuilding.csv')

In [57]:
wifidf = pd.read_csv('wifidfnew.csv')
validationdf = pd.read_csv('validationwithbuilding.csv')
#validationdf2 = pd.read_csv('validationdfnew.csv')

In [58]:
X_train = wifidf.iloc[:, 1:521]
X_train = X_train.replace(100, -1000)
X_train = X_train.astype(float)
X_train = 10**(X_train/10)
y_train = wifidf.iloc[:, 523]

In [59]:
validationdf

,Unnamed: 0,WAP001,WAP002,WAP003,WAP004,WAP005,WAP006,WAP007,WAP008,WAP009,...,WAP512,WAP513,WAP514,WAP515,WAP516,WAP517,WAP518,WAP519,WAP520,BUILDINGID
0,0,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,0
1,1,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,0
2,2,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,0
3,3,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,0
4,4,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5174,5174,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,1
5175,5175,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,1
5176,5176,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,1
5177,5177,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,1
5178,5178,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,1

In [60]:
X_validation = validationdf.iloc[:, 1:521]
X_validation = X_validation.replace(100, -1000)
X_validation = X_validation.astype(float)
X_validation = 10**(X_validation/10)
#y_validation = validationdf2.iloc[:, 523]

In [61]:
modelknn = KNeighborsClassifier(n_neighbors = 4, weights = 'distance', p = 1)
modelknn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=1,
                     weights='distance')

In [62]:
predictions = modelknn.predict(X_validation)
predictions

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [42]:
y_validation

0       3
1       2
2       3
3       4
4       1
       ..
5257    0
5258    1
5259    2
5260    3
5261    0
Name: FLOOR, Length: 5262, dtype: int64

In [43]:
confusion = confusion_matrix(y_validation, predictions)
print("Confusion matrix:\n{}".format(confusion))

Confusion matrix:
[[1104    9    2    0    0]
 [  11 1324   14    4    0]
 [   2   20 1204   13    0]
 [  14    0   14 1244   11]
 [   0    0    0    5  267]]

In [44]:
accuracy = accuracy_score(y_validation, predictions)
accuracy

0.9773850247054352

In [63]:
predictions = pd.DataFrame(predictions)
predictions.columns = ['FLOOR']
submissionfile = pd.concat([wifidfwithbuilding, predictions], axis=1)
submissionfile.to_csv('submissionfile.csv')

In [66]:
wifidf = pd.read_csv('wifidfnew.csv')
validationdf = pd.read_csv('validationwithbuilding.csv')
#validationdf2 = pd.read_csv('validationdfnew.csv')

In [67]:
X_train = wifidf.iloc[:, 1:521]
X_train = X_train.replace(100, 0)
X_train[X_train < -78] = 1
X_train[X_train < 0] = 2
X_train = pd.concat([X_train, wifidf.iloc[:, 524]], axis=1)
y_train = wifidf.iloc[:, 522]

In [68]:
X_validation = validationdf.iloc[:, 1:521]
X_validation = X_validation.replace(100, 0)
X_validation[X_validation < -78] = 1
X_validation[X_validation < 0] = 2
X_validation = pd.concat([X_validation, validationdf.iloc[:, 521]], axis=1)
#y_validation = validationdf2.iloc[:, 522]

In [69]:
modelknn = neighbors.KNeighborsRegressor(n_neighbors = 7, weights = 'distance')
modelknn.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                    weights='distance')

In [70]:
predictions = modelknn.predict(X_validation)
predictions

array([4864980.7377257 , 4864981.47902643, 4864981.47902643, ...,
       4864872.98979443, 4864872.41648142, 4864872.41648142])

In [61]:
y_validation

0       4.864795e+06
1       4.864867e+06
2       4.864890e+06
3       4.864822e+06
4       4.864813e+06
            ...
5257    4.864930e+06
5258    4.864825e+06
5259    4.864890e+06
5260    4.864842e+06
5261    4.864801e+06
Name: LATITUDE, Length: 5262, dtype: float64

In [64]:
MAE = sum(abs(y_validation - predictions))/len(predictions)
predRsquared = r2_score(y_validation,predictions)

In [65]:
#Make Predictions
print('R Squared: %.3f' % predRsquared)
print('MAE: %.3f' % MAE)

R Squared: 0.990
MAE: 2.480

In [71]:
predictions = pd.DataFrame(predictions)
predictions.columns = ['LATITUDE']
submissionfile = pd.concat([submissionfile, predictions], axis=1)
submissionfile.to_csv('submissionfile.csv')

In [72]:
wifidf = pd.read_csv('wifidfnew.csv')
validationdf = pd.read_csv('validationwithbuilding.csv')
#validationdf2 = pd.read_csv('validationdfnew.csv')

In [73]:
X_train = wifidf.iloc[:, 1:521]
X_train = X_train.replace(100, 0)
X_train[X_train < -78] = 1
X_train[X_train < 0] = 2
X_train = pd.concat([X_train, wifidf.iloc[:, 524]], axis=1)
y_train = wifidf.iloc[:, 521]

In [74]:
X_validation = validationdf.iloc[:, 1:521]
X_validation = X_validation.replace(100, 0)
X_validation[X_validation < -78] = 1
X_validation[X_validation < 0] = 2
X_validation = pd.concat([X_validation, validationdf.iloc[:, 521]], axis=1)
#y_validation = validationdf2.iloc[:, 521]

In [75]:
modelknmodelknn = neighbors.KNeighborsRegressor(n_neighbors = 6, weights = 'distance')
modelknn.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                    weights='distance')

In [76]:
predictions = modelknn.predict(X_validation)
predictions

array([-7595.71190417, -7596.1844308 , -7596.1844308 , ...,
       -7570.49105041, -7570.76162199, -7570.76162199])

In [73]:
y_validation

0      -7316.963900
1      -7562.186200
2      -7516.198400
3      -7332.108800
4      -7309.849300
           ...
5257   -7643.993800
5258   -7338.488833
5259   -7516.088800
5260   -7367.458800
5261   -7314.611700
Name: LONGITUDE, Length: 5262, dtype: float64

In [74]:
MAE = sum(abs(y_validation - predictions))/len(predictions)
predRsquared = r2_score(y_validation,predictions)

In [75]:
#Make Predictions
print('R Squared: %.3f' % predRsquared)
print('MAE: %.3f' % MAE)

R Squared: 0.995
MAE: 2.902

In [77]:
predictions = pd.DataFrame(predictions)
predictions.columns = ['LONGITUDE']
submissionfile = pd.concat([submissionfile, predictions], axis=1)
submissionfile.to_csv('submissionfile.csv')

In [78]:
submissionfile = pd.read_csv('submissionfile.csv')

In [79]:
submissionfile.head()

,Unnamed: 0,WAP001,WAP002,WAP003,WAP004,WAP005,WAP006,WAP007,WAP008,WAP009,...,WAP515,WAP516,WAP517,WAP518,WAP519,WAP520,BUILDINGID,FLOOR,LATITUDE,LONGITUDE
0,0,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,0,1,4.864981e+06,-7595.711904
1,1,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,0,1,4.864981e+06,-7596.184431
2,2,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,0,1,4.864981e+06,-7596.184431
3,3,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,0,1,4.864982e+06,-7596.515524
4,4,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,0,1,4.864982e+06,-7596.515524

In [81]:
submissionfile = submissionfile.iloc[:, 521:525]

In [82]:
submissionfile.to_csv('submissionfile.csv')